package views

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import (
	"admincoretest/app/api/protos"

	"github.com/ma-guo/niuhe"
)

type _Gen_System struct{}

// 测试  api
func (v *_Gen_System) Test_GET(c *niuhe.Context, req *protos.SystemTestReq, rsp *protos.NoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 测试  api
func (v *_Gen_System) Test_PUT(c *niuhe.Context, req *protos.NoneReq, rsp *protos.NoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 项目文档
func (v *_Gen_System) Docs_GET(c *niuhe.Context, req *protos.NoneReq, rsp *protos.NoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 测试 rpc
func (v *_Gen_System) Rpc(c *niuhe.Context, req *protos.SystemRpcReqMsg, rsp *protos.SystemRpcRspMsg) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}
