package views

// Generated by niuhe.idl

import (
	"admincoretest/app/api/protos"

	"github.com/ziipin-server/niuhe"
)

type _Gen_System struct{}

// 测试  api
func (v *_Gen_System) Test_GET(c *niuhe.Context, req *protos.NoneReq, rsp *protos.NoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}
