package views

// Generated by niuhe.idl

import (
	"admincoretest/app/api/protos"
	"admincoretest/config"
	"encoding/json"
	"net/http"
	"os"

	"github.com/ma-guo/niuhe"
)

type System struct {
	_Gen_System
}

// 测试  api
func (v *System) Test_GET(c *niuhe.Context, req *protos.NoneReq, rsp *protos.NoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 测试  api
func (v *System) Test_PUT(c *niuhe.Context, req *protos.NoneReq, rsp *protos.NoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 项目文档 /api/system/docs/ 已加入验证的 skipUrl 中
func (v *System) Docs_GET(c *niuhe.Context, req *protos.NoneReq, rsp *protos.NoneRsp) error {
	docs, err := os.ReadFile(config.Config.Docs)
	if err != nil {
		niuhe.LogInfo("read docs error: %v", err)
		return err
	}
	data := make(map[string]interface{})
	json.Unmarshal(docs, &data)
	c.JSON(http.StatusOK, data)
	// 自己处理了输出, 就不走系统输出了
	c.IgnoreResult()
	return nil
}

// 测试 rpc
func (v *System) Rpc(c *niuhe.Context, req *protos.SystemRpcReqMsg, rsp *protos.SystemRpcRspMsg) error {
	return niuhe.NewCommError(-1, "Not Implemented, 在 init.go 中会有 log 日志")
}

func init() {
	GetModule().Register(&System{})
}
