

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

interface Rsp<T> {
    result: number
    data: T
    message: string
}

declare namespace Admincoretest {
    interface NoneRsp {
    }

    interface SystemTestReq {
        /** 输入一个词 */
        world: string,
    }

    interface NoneReq {
    }

    /** 测试 rpc返回参数 */
    interface SystemRpcRspMsg {
    }

    /** 测试 rpc请求参数 */
    interface SystemRpcReqMsg {
        /** 输入一个词 */
        world: string,
        /** 输入一个文本 */
        text: string,
    }

}
