
// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import { ajax_get, ajax_post, ajax_any } from "./request";

 /**
  * 测试  api 
  * @path get /api/system/test/
  * @return Admincoretest.NoneRsp
*/
 export const getApiSystemTest = (data: Admincoretest.SystemTestReq): Promise<Rsp<Admincoretest.NoneRsp>> => {
    return ajax_any("get", "/api/system/test/", data);
 }

 /**
  * 测试  api 
  * @path put /api/system/test/
  * @return Admincoretest.NoneRsp
*/
 export const putApiSystemTest = (data: Admincoretest.NoneReq): Promise<Rsp<Admincoretest.NoneRsp>> => {
    return ajax_any("put", "/api/system/test/", data);
 }

 /**
  * 项目文档 
  * @path get /api/system/docs/
  * @return Admincoretest.NoneRsp
*/
 export const getApiSystemDocs = (data: Admincoretest.NoneReq): Promise<Rsp<Admincoretest.NoneRsp>> => {
    return ajax_any("get", "/api/system/docs/", data);
 }

 /**
  * 测试 rpc 
  * @path get /api/system/rpc/
  * @return Admincoretest.SystemRpcRspMsg
  * @codes 错误码如下
  * - NOTFOUND(404) 未找到
  * - SERVERERROR(500) 服务器错误
*/
 export const getApiSystemRpc = (data: Admincoretest.SystemRpcReqMsg): Promise<Rsp<Admincoretest.SystemRpcRspMsg>> => {
    return ajax_any("get", "/api/system/rpc/", data);
 }

 /**
  * 测试 rpc 
  * @path post /api/system/rpc/
  * @return Admincoretest.SystemRpcRspMsg
  * @codes 错误码如下
  * - NOTFOUND(404) 未找到
  * - SERVERERROR(500) 服务器错误
*/
 export const postApiSystemRpc = (data: Admincoretest.SystemRpcReqMsg): Promise<Rsp<Admincoretest.SystemRpcRspMsg>> => {
    return ajax_any("post", "/api/system/rpc/", data);
 }

