package protos

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改, 不需要生成本文件时请在 langs 中移除 route 配置

// niuhe 生成的路由结构
type RouteItem struct {
	Method string `json:"method"` // API 请求方法
	Path   string `json:"path"`   // API 请求路径
	Name   string `json:"name"`   // API 名称
}

// api 模块下的所有路由数组
var RouteItems = []*RouteItem{
	{Method: "GET", Path: "/api/system/test/", Name: "测试  api"},
	{Method: "PUT", Path: "/api/system/test/", Name: "测试  api"},
	{Method: "GET", Path: "/api/system/docs/", Name: "项目文档"},
}
