package protos

// Generated by niuhe.idl

type NoneReq struct {
}

type NoneRsp struct {
}

type SystemTestReq struct {
	World string `json:"world" zpf_name:"world" zpf_reqd:"true"` //	输入一个词	 示例: hello world
}
