package protos

import (
	"admincoretest/app/common/consts"

	"github.com/ma-guo/niuhe"
)

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改, 不需要生成本文件时请在 langs 中移除 route 配置

// api 模块下的所有路由数组
var RouteItems = []*niuhe.RouteItem{
	{Method: "GET", Path: "/api/system/test/", Name: "测试  api"},
	{Method: "PUT", Path: "/api/system/test/", Name: "测试  api"},
	{Method: "GET", Path: "/api/system/docs/", Name: "项目文档"},
	{Method: "GET", Path: "/api/system/rpc/", Name: "测试 rpc", Codes: []niuhe.IntConstItem{
		consts.ErrorEnum.NOT_FOUND,    // 404 - 未找到
		consts.ErrorEnum.SERVER_ERROR, // 500 - 服务器错误,
	}},
	{Method: "POST", Path: "/api/system/rpc/", Name: "测试 rpc", Codes: []niuhe.IntConstItem{
		consts.ErrorEnum.NOT_FOUND,    // 404 - 未找到
		consts.ErrorEnum.SERVER_ERROR, // 500 - 服务器错误,
	}},
}
