package consts

// Generated by niuhe.idl

import "github.com/ma-guo/niuhe"

var ErrorEnum struct {
	*niuhe.IntConstGroup
	NOT_FOUND    niuhe.IntConstItem `name:"未找到" value:"404"`   // value: 404, name: 未找到
	SERVER_ERROR niuhe.IntConstItem `name:"服务器错误" value:"500"` // value: 500, name: 服务器错误
}

func init() {
	niuhe.InitIntConstGroup(&ErrorEnum)
}
